version: '3'

services:

  plex:
    build: .
    restart: unless-stopped
    expose:
      - 32400
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
#      - "80:80/tcp"
      #- "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    hostname: plex_server
    environment:
      - PLEX_USERNAME=${PLEX_USERNAME}
      - PLEX_PASSWORD=${PLEX_PASSWORD}
    volumes:
      - /tmp/transcode:/transcode
      - /tmp/movies:/movies
      - /tmp/tv:/tv
